stages:
  train:
    cmd: python train.py --img 1000 --batch 16 --epochs 1 --data coco128.yaml --weights yolov5s.pt --cache
    deps:
    - train.py
    - params.yml
    outs:
      - runs/train:
          persist: true
      - datasets/coco128:
          persist: true