stages:
  install:
    cmd: pip install -r requirements.txt
    deps:
      - requirements.txt
  train:
    cmd: python train.py --data coco128.yaml --cfg yolov5s.yaml --weights '' --batch-size 64
    deps:
    - data/coco128
    - train.py
    outs:
      - models:
          persist: true